__author__ = 'rodtoll'

# Interface and service names
SERVICE_NAME = "org.bluez"
BLUEZ_ADAPTER_INTERFACE = SERVICE_NAME + ".Adapter"
BLUEZ_DEVICE_INTERFACE = SERVICE_NAME + ".Device"
BLUEZ_MANAGER_INTERFACE = SERVICE_NAME + ".Manager"

NO_DEVICE_NAME = "<NONE>"

# Property Names
BLUEZ_DEVICE_PROPERTY_NAME = "Name"
BLUEZ_DEVICE_PROPERTY_ADDRESS = "Address"
BLUEZ_DEVICE_PROPERTY_RSSI = "RSSI"
BLUEZ_DEVICE_PROPERTY_POWERED = "Powered"

# Signal Names
BLUEZ_ADAPTER_SIGNAL_DEVICE_ADDED = "DeviceFound"
BLUEZ_ADAPTER_SIGNAL_DEVICE_GONE = "DeviceDisappeared"
BLUEZ_ADAPTER_SIGNAL_PROPERTY_CHANGED = "PropertyChanged"
